export const LOAD_USERS_TO_STORE = 'LOAD_USERS_TO_STORE';
export const ADD_USER_TO_STORE = 'ADD_USER_TO_STORE';
export const REMOVE_USER_FROM_STORE = 'REMOVE_USER_FROM_STORE';
export const UPDATE_USER_IN_STORE = 'UPDATE_USER_IN_STORE';